feat: add color to github actions output
snyk/actions pull request #94
Opened 2022-05-13 15:18 UTC by kevin-s31

Added the FORCE_COLOR environment variable and set it to true to see a colored output for a snyk test in github actions

2022-05-13 15:22 UTC, garethr requested changes

2022-05-13 15:22 UTC, garethr commented on setup/setup_snyk.sh
> +    echo export FORCE_COLOR= True
I think the space after `=` will cause this to not work?

2022-05-13 15:25 UTC, garethr commented
Note I think `supports-color` uses the following. Not sure if `True` works, or works as well as for instance 2 or 3?

```
If FORCE_COLOR is "0" or "false" then force plain, uncolored output
If FORCE_COLOR is "1" or "true" then force 16 color ANSI output
If FORCE_COLOR is "2" then force 256 color ANSI output
If FORCE_COLOR is "3" then force full 24-bit RGB output
```

Might be worth trying out, and posting a screenshot of it working in this PR to demonstrate this works as intended?

2022-05-13 15:27 UTC, kevin-s31 commented
Will check on both of the above.

2022-05-13 15:54 UTC, kevin-s31 commented
Removed the space after the variable and also instead of True, set it to 2 to allow for 256 color ANSI output

2022-05-19 11:22 UTC, bastiandoetsch approved these changes
LGTM

2022-05-19 11:22 UTC, merged